db:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
#             ----- CHANGE MOUNT ROUTE ----- 
    - /home/"USERNAME"/db:/var/lib/mysq
  environment:
    MYSQL_ROOT_PASSWORD: h4ck3d
    MYSQL_USER: root
    MYSQL_PASSWORD: h4ck3d
    MYSQL_DATABASE: prueba
web:
  image: kpu27/ubuntu-lamp
  links:
    - db
  ports:
    - "4040:80"
    - "8080:8080"
    - "5000:5000"
  volumes:
#             ----- CHANGE MOUNT ROUTE -----
    - /home/"USERNAME"/web:/var/www/html
